services:
  db:
    platform: linux/arm64
    image: postgres:latest
    hostname: db-tinymcp
    container_name: db-tinymcp
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - db
    volumes:
      - db:/var/lib/postgresql
    command: postgres -c client_encoding=utf8
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      start_period: 10s
      interval: 5s
      timeout: 3s
      retries: 3
 

  server:
    platform: linux/arm64
    hostname: server-tinymcp
    container_name: server-tinymcp
    restart: unless-stopped
    working_dir: /workdir
    environment:
      PYTHONPATH: /workdir
    build:
      context: .
      dockerfile: dockerfile
      target: local
      args:
        ENV: local
        WORK_DIR: /workdir
        INSTALL_DIR: /opt/install
        PW_DIR: /pwdir
    ports:
      - "8000:8000"
    volumes:
      - .:/workdir
    networks:
      - db
      - server
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "fastmcp run src/server.py:mcp --transport http --port 8000"


networks:
  db:
    name: db-tinymcp
    driver: bridge
  server:
    name: server-tinymcp
    driver: bridge


volumes:
  db:
    name: db-tinymcp

